import type { AssessmentGrade, AssessmentInput } from "@/lib/ai/llm-client";
import { formatDateLong } from "@/lib/dates";

/**
 * Builds the daily trainer email. Pure string functions only — no network,
 * no database, no server-only imports — so both callers can share them:
 *
 *   - the daily job (lib/jobs/daily-assessment.ts), which actually sends it
 *   - the "Send to Trainer" button in app/assessment/AssessmentClient.tsx,
 *     which opens a pre-filled Gmail compose window
 *
 * Keeping one copy is the point: if the two drifted, the automatic email
 * and the manual one would say different things about the same day.
 */

export const TRAINER_EMAIL = "786zafarabdul@gmail.com";

const ATHLETE_NAME = "Sam Rao";

export interface TrainerEmailData {
  yesterdayDate: string;
  input: AssessmentInput;
  yesterdayWorkoutNames: string[];
  shortAssessment: string;
  grade: AssessmentGrade;
}

export interface TrainerEmail {
  to: string;
  subject: string;
  body: string;
}

function formatWeight(value: number | null): string {
  return value === null ? "Not set" : String(value);
}

/** e.g. "Weight: 290 lbs (Start: 295 / Goal: 210)". */
function buildWeightLine(input: AssessmentInput): string {
  const current = formatWeight(input.weight_lbs_current);
  const currentWithUnit = input.weight_lbs_current === null ? current : `${current} lbs`;
  const start = formatWeight(input.weight_lbs_start);
  const goal = formatWeight(input.weight_lbs_goal);
  return `Weight: ${currentWithUnit} (Start: ${start} / Goal: ${goal})`;
}

/** e.g. "Nutrition: 1769 cal, 171g protein", or "Nutrition: Not logged". */
function buildNutritionLine(input: AssessmentInput): string {
  if (input.yesterday_calories === null || input.yesterday_protein_g === null) {
    return "Nutrition: Not logged";
  }
  return `Nutrition: ${input.yesterday_calories} cal, ${input.yesterday_protein_g}g protein`;
}

/** e.g. "Workout: Push Day (31,760 lbs total volume)", or "Workout: None logged". */
function buildWorkoutLine(input: AssessmentInput, workoutNames: string[]): string {
  if (input.yesterday_workout_present !== 1) {
    return "Workout: None logged";
  }
  const volume = input.yesterday_workout_volume_lbs?.toLocaleString();
  return `Workout: ${workoutNames.join(" · ")} (${volume} lbs total volume)`;
}

export function buildTrainerEmail(data: TrainerEmailData): TrainerEmail {
  const subject = `Daily Assessment for ${ATHLETE_NAME} — ${formatDateLong(data.yesterdayDate)}`;

  const body = [
    buildWeightLine(data.input),
    buildNutritionLine(data.input),
    buildWorkoutLine(data.input, data.yesterdayWorkoutNames),
    "",
    data.shortAssessment,
    "Grade: " + data.grade,
    "",
    `— Generated by Fat Loss Tracker for ${ATHLETE_NAME}`,
  ].join("\n");

  return { to: TRAINER_EMAIL, subject, body };
}

/**
 * A Gmail compose URL pre-filled with the same email, for the manual
 * "Send to Trainer" button.
 *
 * Uses `encodeURIComponent` rather than `URLSearchParams` deliberately:
 * URLSearchParams encodes spaces as "+", and while Gmail reads that as a
 * space, this URL shape is already known to work in production. The one
 * change from the original is that `to` is now encoded too — it was being
 * interpolated raw.
 */
export function buildTrainerComposeHref(data: TrainerEmailData): string {
  const { to, subject, body } = buildTrainerEmail(data);
  return (
    "https://mail.google.com/mail/?view=cm" +
    "&to=" + encodeURIComponent(to) +
    "&su=" + encodeURIComponent(subject) +
    "&body=" + encodeURIComponent(body)
  );
}
