import { describe, it, expect } from "vitest";
import {
  buildTrainerEmail,
  buildTrainerComposeHref,
  TRAINER_EMAIL,
} from "@/lib/email/trainer-email";
import type { AssessmentInput } from "@/lib/ai/llm-client";

const FULL_INPUT: AssessmentInput = {
  weight_lbs_start: 295,
  weight_lbs_goal: 210,
  weight_lbs_current: 290,
  yesterday_calories: 1769,
  yesterday_protein_g: 171,
  yesterday_workout_present: 1,
  yesterday_workout_volume_lbs: 31760,
};

const EMPTY_INPUT: AssessmentInput = {
  weight_lbs_start: null,
  weight_lbs_goal: null,
  weight_lbs_current: null,
  yesterday_calories: null,
  yesterday_protein_g: null,
  yesterday_workout_present: 0,
  yesterday_workout_volume_lbs: null,
};

const BASE = {
  yesterdayDate: "2026-08-07",
  yesterdayWorkoutNames: ["Push Day"],
  shortAssessment: "Solid day. Protein on target.",
  grade: "A+" as const,
};

describe("buildTrainerEmail", () => {
  it("addresses the trainer and dates the subject in the assessed day, not today", () => {
    const email = buildTrainerEmail({ ...BASE, input: FULL_INPUT });

    expect(email.to).toBe(TRAINER_EMAIL);
    expect(email.subject).toBe("Daily Assessment for Sam Rao — Aug 7, 2026");
  });

  it("includes weight, nutrition, workout, the assessment and the grade", () => {
    const { body } = buildTrainerEmail({ ...BASE, input: FULL_INPUT });

    expect(body).toContain("Weight: 290 lbs (Start: 295 / Goal: 210)");
    expect(body).toContain("Nutrition: 1769 cal, 171g protein");
    expect(body).toContain("Workout: Push Day (31,760 lbs total volume)");
    expect(body).toContain("Solid day. Protein on target.");
    expect(body).toContain("Grade: A+");
    expect(body).toContain("— Generated by Fat Loss Tracker for Sam Rao");
  });

  it("joins multiple workout names", () => {
    const { body } = buildTrainerEmail({
      ...BASE,
      input: FULL_INPUT,
      yesterdayWorkoutNames: ["Morning Run", "Evening Lift"],
    });

    expect(body).toContain("Workout: Morning Run · Evening Lift (31,760 lbs total volume)");
  });

  // The job sends every day, including days with gaps — an unlogged day is
  // itself information the trainer wants, so it must render honestly rather
  // than as a zero.
  it("says 'Not logged' for nutrition rather than reporting zero calories", () => {
    const { body } = buildTrainerEmail({ ...BASE, input: EMPTY_INPUT });

    expect(body).toContain("Nutrition: Not logged");
    expect(body).not.toContain("0 cal");
  });

  it("says 'None logged' for a missing workout", () => {
    const { body } = buildTrainerEmail({
      ...BASE,
      input: EMPTY_INPUT,
      yesterdayWorkoutNames: [],
    });

    expect(body).toContain("Workout: None logged");
  });

  it("renders unset weights as 'Not set' without a stray unit", () => {
    const { body } = buildTrainerEmail({ ...BASE, input: EMPTY_INPUT });

    expect(body).toContain("Weight: Not set (Start: Not set / Goal: Not set)");
    expect(body).not.toContain("Not set lbs");
  });
});

describe("buildTrainerComposeHref", () => {
  it("encodes the recipient, subject and body", () => {
    const href = buildTrainerComposeHref({ ...BASE, input: FULL_INPUT });

    // The "@" in the address must be encoded — it was interpolated raw before.
    expect(href).toContain(`to=${encodeURIComponent(TRAINER_EMAIL)}`);
    expect(href).not.toContain(`to=${TRAINER_EMAIL}`);
    // Newlines survive as %0A rather than breaking the URL.
    expect(href).toContain("%0A");
    expect(href.startsWith("https://mail.google.com/mail/?view=cm")).toBe(true);
  });

  it("sends the same subject and body the job emails", () => {
    const data = { ...BASE, input: FULL_INPUT };
    const email = buildTrainerEmail(data);
    const href = buildTrainerComposeHref(data);

    expect(href).toContain(encodeURIComponent(email.subject));
    expect(href).toContain(encodeURIComponent(email.body));
  });
});
